#!/usr/bin/env python3
"""Unattended overnight queue: train several sign detectors, then rank them.

Runs start to finish on its own. Launch it, walk away, read runs/overnight/
REPORT.md in the morning. Nothing here needs a live assistant session -- the GPU
work happens in detached subprocesses, so the queue survives the terminal, and
each stage appends to the report the moment it finishes rather than at the end.

Why three models instead of one long run: the right answer depends on a number
that can only be measured ON THE PI tomorrow -- how long inference actually
takes at imgsz 640. The CPU path measured 5.45 ms mean / 8.16 ms p99 at imgsz
320 against a 66 ms budget (15 Hz), so 640 should fit with room to spare, but
"should" is not "does". The queue therefore produces:

  n640   yolov8n at 640 -- the drop-in upgrade, matching the camera's geometry
  s640   yolov8s at 640 -- spends the measured CPU headroom on capacity
  n320   yolov8n at 320 -- the fallback if 640 turns out too slow on the Pi

Ordered by value, and each one is capped by wall clock (Ultralytics `time=`),
so an overrun in the first run cannot starve the others and every stage still
writes a usable best.pt.

Ranking uses tools/eval_hard.py on car_hard: degraded copies of the TEST split,
which no run trains on. mAP on the clean set is useless for this decision --
every variant scores ~0.995 there and the metric cannot tell them apart.

Usage:
    python TMR2026/tools/overnight_signs.py
    python TMR2026/tools/overnight_signs.py --budget 6.0
    python TMR2026/tools/overnight_signs.py --skip-baseline
"""
from __future__ import annotations

import argparse
import subprocess
import sys
import time
from datetime import datetime, timedelta
from pathlib import Path

HERE = Path(__file__).resolve().parent
TMR_ROOT = HERE.parent
REPO_ROOT = TMR_ROOT.parent

DATASETS = TMR_ROOT / "datasets"
OUT = REPO_ROOT / "runs" / "overnight"
REPORT = OUT / "REPORT.md"
MERGED = DATASETS / "merged_signs.yaml"

CLASS_NAMES = ["green", "left", "red", "right", "stop", "straight", "yellow"]

PY = sys.executable


# Fractions of the total budget. Sum < 1.0 -- the remainder covers evaluation.
#
# Measured on this GPU with the merged 5398-image set: ~6.1 min/epoch at imgsz
# 640 batch 16. So a 6 h budget buys roughly 20 epochs at 640 and 35 at 320 --
# ample for the two fine-tunes, which start from an already-converged
# tmr_signs.pt, and thin for s640, which starts from COCO weights.
#
# Order is deliberate. The two fine-tunes are cheap and are the models most
# likely to ship, so they finish first; s640 is the speculative capacity probe
# and sits last, where truncation costs the least.
QUEUE = [
    dict(tag="n640", model=TMR_ROOT / "weights" / "tmr_signs.pt",
         imgsz=640, batch=16, frac=0.333, epochs=300,
         note="drop-in upgrade at the camera's native geometry"),
    dict(tag="n320", model=TMR_ROOT / "weights" / "tmr_signs.pt",
         imgsz=320, batch=32, frac=0.150, epochs=300,
         note="fallback if imgsz 640 is too slow on the Pi"),
    dict(tag="s640", model="yolov8s.pt",
         imgsz=640, batch=8, frac=0.450, epochs=300,
         note="capacity probe; starts from COCO so it gets the longest slot"),
]


def log(msg: str) -> None:
    stamp = datetime.now().strftime("%H:%M:%S")
    print(f"[{stamp}] {msg}", flush=True)


def say(md: str) -> None:
    """Append to the report immediately, so a crash still leaves a record."""
    with REPORT.open("a", encoding="utf-8") as f:
        f.write(md + "\n")
    print(md, flush=True)


def write_merged_yaml() -> bool:
    """Point training at car_domain + synth_signs, validate on real frames only.

    Validation deliberately excludes the synthetic composites: best.pt is chosen
    by val score, and picking a model because it is good at its own synthetic
    pixels would be circular.
    """
    train_dirs, val_dirs = [], []
    for name in ("car_domain", "synth_signs"):
        d = DATASETS / name / "train" / "images"
        if d.is_dir() and any(d.iterdir()):
            train_dirs.append(f"{name}/train/images")
    d = DATASETS / "car_domain" / "valid" / "images"
    if d.is_dir() and any(d.iterdir()):
        val_dirs.append("car_domain/valid/images")

    if not train_dirs or not val_dirs:
        return False

    lines = [
        "# Generated by tools/overnight_signs.py -- safe to delete.",
        f"path: {DATASETS.as_posix()}",
        "train:",
        *[f"  - {p}" for p in train_dirs],
        "val:",
        *[f"  - {p}" for p in val_dirs],
        "",
        f"nc: {len(CLASS_NAMES)}",
        f"names: {CLASS_NAMES}",
        "",
    ]
    MERGED.write_text("\n".join(lines), encoding="utf-8")
    log(f"merged dataset -> {MERGED}")
    for p in train_dirs:
        n = len(list((DATASETS / p).iterdir()))
        log(f"    train  {p:32} {n:6d} images")
    for p in val_dirs:
        n = len(list((DATASETS / p).iterdir()))
        log(f"    val    {p:32} {n:6d} images")
    return True


def run(cmd: list[str], logfile: Path, timeout_s: float) -> int:
    """Run a subprocess, tee-ing to a log. Returns the exit code (124 = timeout)."""
    logfile.parent.mkdir(parents=True, exist_ok=True)
    with logfile.open("w", encoding="utf-8", errors="replace") as f:
        f.write(" ".join(str(c) for c in cmd) + "\n\n")
        f.flush()
        p = subprocess.Popen([str(c) for c in cmd], stdout=f,
                             stderr=subprocess.STDOUT, cwd=str(REPO_ROOT))
        try:
            return p.wait(timeout=timeout_s)
        except subprocess.TimeoutExpired:
            p.kill()
            p.wait()
            return 124


def train_one(spec: dict, hours: float) -> Path | None:
    """One training run, with a single reduced-batch retry on OOM."""
    name = f"signs_{spec['tag']}"
    best = OUT / name / "weights" / "best.pt"
    batch = spec["batch"]

    for attempt in (1, 2):
        cmd = [
            PY, str(HERE / "train_signs.py"),
            "--data", str(MERGED),
            "--model", str(spec["model"]),
            "--imgsz", str(spec["imgsz"]),
            "--batch", str(batch),
            "--epochs", str(spec["epochs"]),
            "--time", f"{hours:.3f}",
            "--recipe", "cardomain",
            "--patience", "100",
            "--project", str(OUT),
            "--name", name,
            "--workers", "4",
        ]
        log(f"train {spec['tag']}: imgsz={spec['imgsz']} batch={batch} "
            f"cap={hours:.2f} h  ({spec['note']})")

        # +25 min of slack: Ultralytics checks its clock between epochs, and
        # still has to run the final validation pass after the cap trips.
        rc = run(cmd, OUT / f"{name}.log", hours * 3600 + 1500)

        if best.exists():
            log(f"train {spec['tag']}: done (rc={rc}) -> {best}")
            return best

        tail = ""
        lf = OUT / f"{name}.log"
        if lf.exists():
            tail = lf.read_text(encoding="utf-8", errors="replace")[-2500:]
        oom = "out of memory" in tail.lower() or "CUDA out of memory" in tail

        if oom and attempt == 1 and batch > 2:
            batch = max(2, batch // 2)
            log(f"train {spec['tag']}: OOM -> retrying at batch {batch}")
            continue

        log(f"train {spec['tag']}: FAILED (rc={rc}), no best.pt")
        say(f"\n### {spec['tag']} — FAILED (rc={rc})\n"
            f"```\n{tail[-1200:]}\n```")
        return None
    return None


def evaluate(weights: Path, label: str, sizes: str) -> str:
    cmd = [PY, str(HERE / "eval_hard.py"),
           "--weights", str(weights), "--imgszs", sizes]
    try:
        r = subprocess.run([str(c) for c in cmd], cwd=str(REPO_ROOT),
                           capture_output=True, text=True, timeout=3600)
        out = r.stdout.strip() or r.stderr.strip()
    except subprocess.TimeoutExpired:
        out = "(evaluation timed out)"
    say(f"\n### {label}\n\n```\n{out}\n```")
    return out


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--budget", type=float, default=6.0,
                    help="total wall-clock hours for the whole queue")
    ap.add_argument("--skip-baseline", action="store_true")
    ap.add_argument("--sizes", default="320,640",
                    help="inference sizes to evaluate every model at")
    args = ap.parse_args()

    OUT.mkdir(parents=True, exist_ok=True)
    started = datetime.now()
    eta = started + timedelta(hours=args.budget)

    REPORT.write_text(
        f"# Overnight sign-detector training\n\n"
        f"- started **{started:%Y-%m-%d %H:%M}**, budget **{args.budget:.1f} h**, "
        f"expected done ~**{eta:%H:%M}**\n"
        f"- benchmark: `TMR2026/datasets/car_hard` — degraded copies of the "
        f"Roboflow TEST split, which no run trains on\n"
        f"- the number that matters is **R@gate for stop/red**: the share of "
        f"real signs clearing conf 0.55, the threshold that brakes the car\n",
        encoding="utf-8")

    if not write_merged_yaml():
        say("\n**ABORTED** — datasets missing. Run first:\n\n"
            "```\npython TMR2026/tools/make_car_domain.py --copies 2\n"
            "python TMR2026/tools/synth_signs.py --count 2500\n```")
        sys.exit(1)

    hard = DATASETS / "car_hard" / "val" / "images"
    if not hard.is_dir() or not any(hard.iterdir()):
        say("\n**ABORTED** — no benchmark at car_hard/val/images.")
        sys.exit(1)

    if not args.skip_baseline:
        cur = TMR_ROOT / "weights" / "tmr_signs.pt"
        if cur.exists():
            log("baseline evaluation (the model currently on the car)...")
            say("\n---\n\n## Baseline — the model deployed right now")
            evaluate(cur, "tmr_signs.pt (deployed)", args.sizes)

    say("\n---\n\n## Training runs")

    trained: list[tuple[str, Path]] = []
    for spec in QUEUE:
        elapsed = (datetime.now() - started).total_seconds() / 3600.0
        left = args.budget - elapsed
        if left <= 0.25:
            log(f"budget spent ({elapsed:.2f} h) -- skipping {spec['tag']}")
            say(f"\n### {spec['tag']} — skipped, budget spent")
            continue

        hours = min(args.budget * spec["frac"], max(0.2, left - 0.20))
        best = train_one(spec, hours)
        if best:
            trained.append((spec["tag"], best))
            evaluate(best, f"{spec['tag']} — {spec['note']}", args.sizes)

    say("\n---\n\n## Ranking")
    if trained:
        cmp_cmd = [PY, str(HERE / "eval_hard.py"), "--imgszs", args.sizes,
                   "--compare"]
        cur = TMR_ROOT / "weights" / "tmr_signs.pt"
        if cur.exists():
            cmp_cmd.append(str(cur))
        cmp_cmd += [str(p) for _, p in trained]
        try:
            r = subprocess.run([str(c) for c in cmp_cmd], cwd=str(REPO_ROOT),
                               capture_output=True, text=True, timeout=7200)
            body = r.stdout.strip() or r.stderr.strip()
        except subprocess.TimeoutExpired:
            body = "(ranking timed out)"
        say(f"\n```\n{body}\n```")
    else:
        say("\nNo run produced weights.")

    total = (datetime.now() - started).total_seconds() / 3600.0
    say(f"\n---\n\n**Finished {datetime.now():%H:%M}, {total:.2f} h total.**\n")
    say("### Next\n\n"
        "1. Pick the winner from the ranking above — highest **R@gate** for "
        "stop/red, then highest **conf** (margin over 0.55), then fewest FP.\n"
        "2. Measure that model's latency on the Pi before committing to it:\n"
        "   `python TMR2026/tools/bench_ablation.py`. imgsz 640 costs about 4x "
        "imgsz 320; the budget is 66 ms at 15 Hz.\n"
        "3. Deploy: copy best.pt to `TMR2026/weights/tmr_signs.pt`, set the "
        "matching `imgsz` in `vision/sign_detector.py`, then regenerate the "
        "NCNN export with `python TMR2026/tools/export_model.py`.\n")

    log(f"ALL DONE in {total:.2f} h -- report: {REPORT}")


if __name__ == "__main__":
    main()
